site_dir: '../cppmap.github.io'

# Project information
site_name: C++ の歩き方 | CppMap
site_description: C++17, C++20, C++23, C++26 に関する情報を調査・提供します
site_author: Ryo Suzuki
site_url: https://cppmap.github.io/

# Repository
repo_name: cppmap/cppmap.docs
repo_url: https://github.com/cppmap/cppmap.docs
edit_uri: ""

# Copyright
copyright: To the extent possible under law, Ryo Suzuki has waived all copyright and related or neighboring rights to C++ の歩き方 | CppMap. Third party copyrights are property of their respective owners.

# Theme
theme:
  name: 'material'
  language: 'ja'
  favicon: 'assets/images/logo.png'
  logo:
    icon: 'donut_small'
  palette:
    primary: 'teal'
    accent: 'teal'
  feature:
    tabs: true
extra:
  search:
    language: 'en, ja'
    tokenizer: '[\s　、。，．がのをにへとでやかもる「」『』]+'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/Reputeless'
markdown_extensions:
  - admonition
  - codehilite
  - fontawesome_markdown
  - footnotes
  - meta
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.superfences
  - toc:
      permalink: true
extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
  - cppmap_styles.css

# Page tree
nav:
  - Home: index.md
  - C++ 規格:
    - C++20 の新機能: standardization/cpp20.md
    - C++23 以降に向けた提案: standardization/cppx.md
    - 標準化会議: standardization/meetings.md
    - 処理系の対応状況: standardization/status.md
    - C++ 規格書: standardization/working-drafts.md
    - C++ 標準ライブラリ: standardization/header.md
  - 記事:
    - コメントアウトのトリック: articles/comment-tricks.md
    - なぜかコンパイルできる: articles/it-compiles.md
    - なぜかコンパイルできない: articles/it-does-not-compile.md
    - 予約語の読みと名前の由来: articles/how-to-read-keywords.md
    - 標準ライブラリの読みと名前の由来: articles/how-to-read-libraries.md
    - IEEE 754 演算のルール: articles/ieee754-arithmetic.md
    - C++ 関連の略語: articles/acronyms.md
    - C++ 型特性 早見表: articles/type-traits.md
    - C++ アクセス指定子の効果: articles/member-access.md
  - 学習:
    - C++ 書籍: learn/books.md
    - C++ オンライン資料: learn/online-resources.md
    - 国内の C++ 勉強会: learn/studymeetings.md
    - C++ コミュニティ: learn/communities.md
    - C++ カンファレンス: learn/conferences.md
  - ライブラリ:
    - Boost: libraries/boost.md
    - コンテナ: libraries/containers.md
    - テキストデータ: libraries/text-data.md
    - 並行・並列: libraries/concurrency.md
    - テストフレームワーク: libraries/testing.md
    - 数学: libraries/math.md
  - ツール:
    - C++ オンラインコンパイラ: tools/onlinecompilers.md
    - C++ コンパイラ: tools/compilers.md
    - C++ パッケージマネージャ: tools/package-manager.md
    - C++ コードフォーマッタ: tools/code-formatter.md
    - C++ プロジェクトテンプレート: tools/project-template.md
  - 貢献:
    - コントリビュータ: contribution/contributors.md
